APE: false
DEPTHS:
- 2
- 2
- 6
- 2
EMBED_DIM: 96
IN_CHANS: 3
MLP_RATIO: 4.0
NUM_HEADS:
- 3
- 6
- 12
- 24
PATCH_NORM: true
PATCH_SIZE: 4
PRETRAINED_WINDOW_SIZES:
- 0
- 0
- 0
- 0
QKV_BIAS: true
WINDOW_SIZE: 8